### ISSUE TITLE
Spamming home assistant logs

### ISSUE THREAD

**Issue by calipee** [agustin-e/weback-home-assistant-component#1]
Works great, but integration is absolutely spamming the home assistant logs. 

Is there any way to set the log level?

**Comment by agustin-e** [comment]
Hi Calipee, I'll consider adding an option to disable logs... Right now it's only logging at DEBUG level

**Comment by Delta1977** [comment]
something seems wrong.
I set loglevel in HA:
logger:
  default: warning

and in HA-Core-Log it shows all debug logs.

**Comment by agustin-e** [comment]
Hi, have you restarted home assistant after adding 

```
logger:
    default: warning
```

to your Configuration.yaml file? I've just did that and nothing appears in my log.

**Comment by Delta1977** [comment]
> Hi, have you restarted home assistant after adding 
> 
> 
> 
> ```
> 
> logger:
> 
>     default: warning
> 
> ```
> 
> 
> 
> to your Configuration.yaml file? I've just did that and nothing appears in my log.

Yes did. 
But logging from websocket still appears

**Comment by Delta1977** [comment]
Crazy: 
This helped for me:

logger:
  default: warning
  logs:
    websocket: error


Edit: 
Maybe i'm affected by this "bug"

https://community.home-assistant.io/u/u8915055

**Comment by calipee** [comment]
For me its also only working after adding 

>logs:
>websocket: error

@Delta1977 Is your link supposed to be directing to a user profile?
