### ISSUE TITLE
Cool Work, please add this project to HACS / Home Assistant Community Store

### ISSUE THREAD

**Issue by Delta1977** [agustin-e/weback-home-assistant-component#2]
https://hacs.xyz/

**Comment by Delta1977** [comment]
ist already avaible :-)

**Comment by OlafKocanda** [comment]
how is it called? could not find it there
could only find: [opravdin/weback-hass](https://hacs.xyz/docs/repositories/integration/opravdin_weback_hass)

**Comment by Delta1977** [comment]
you had to add this repo as as custom repository:
https://hacs.xyz/docs/faq/custom_repositories
