### ISSUE TITLE
Connection lost after 1 Day

### ISSUE THREAD

**Issue by robotanik** [agustin-e/weback-home-assistant-component#4]
I flowed the setup guide and was able to correctly Set-up my Tesvor X500. Stats are reported correctly and the basic Controls (Start, Stop, Dock, SpotClean) work fine. But after around on day the connection get lost and there are no new status updates and the controls stop working. A restart of Home Assistant fixes the problem. This happens during inactivity and during cleaning. (I can start the cleaning but not stop it because the connection got lost)

**Comment by Delta1977** [comment]
same here
